"""sketches: DB-backed image storage (image_data, image_content_type)

Revision ID: 552b14a44df8
Revises: b8580c819e48
Create Date: 2026-08-16 12:18:31.472295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552b14a44df8'
down_revision: Union[str, Sequence[str], None] = 'b8580c819e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sketches', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('sketches', sa.Column('image_content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sketches', 'image_content_type')
    op.drop_column('sketches', 'image_data')
    # ### end Alembic commands ###
