"""initial schema: projects, users, sketches, decision log, concept families

Revision ID: b8580c819e48
Revises: 
Create Date: 2026-08-16 12:09:25.980137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8580c819e48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lmkc_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('consensus', sa.String(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lmkc_entries_category'), 'lmkc_entries', ['category'], unique=False)
    op.create_index(op.f('ix_lmkc_entries_doc_id'), 'lmkc_entries', ['doc_id'], unique=True)
    op.create_index(op.f('ix_lmkc_entries_id'), 'lmkc_entries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('client_brief', sa.Text(), nullable=False),
    sa.Column('client_contact', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('brand_confidence_score', sa.Float(), nullable=True),
    sa.Column('brand_confidence_level', sa.String(), nullable=True),
    sa.Column('discovery_summary', sa.JSON(), nullable=True),
    sa.Column('brand_dna', sa.JSON(), nullable=True),
    sa.Column('insight_report', sa.JSON(), nullable=True),
    sa.Column('concept_families', sa.JSON(), nullable=True),
    sa.Column('judge_report', sa.JSON(), nullable=True),
    sa.Column('concept_prompts', sa.JSON(), nullable=True),
    sa.Column('ssb', sa.JSON(), nullable=True),
    sa.Column('presentation', sa.JSON(), nullable=True),
    sa.Column('client_persona', sa.JSON(), nullable=True),
    sa.Column('appeal_report', sa.JSON(), nullable=True),
    sa.Column('contest_brief', sa.JSON(), nullable=True),
    sa.Column('contest_feedback', sa.JSON(), nullable=True),
    sa.Column('workshop_state', sa.JSON(), nullable=True),
    sa.Column('workshop_share_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    op.create_index(op.f('ix_projects_workshop_share_token'), 'projects', ['workshop_share_token'], unique=False)
    op.create_table('concept_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('family_label', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('core_meaning_served', sa.Text(), nullable=True),
    sa.Column('family_data', sa.JSON(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('judge_detail', sa.JSON(), nullable=True),
    sa.Column('concept_dna', sa.JSON(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_families_id'), 'concept_families', ['id'], unique=False)
    op.create_table('decision_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('made_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_log_id'), 'decision_log', ['id'], unique=False)
    op.create_table('sketches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sketch_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('design_intent', sa.Text(), nullable=True),
    sa.Column('linked_concept_family', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('coach_feedback', sa.JSON(), nullable=True),
    sa.Column('coach_confidence', sa.String(), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('revision_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sketches_id'), 'sketches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sketches_id'), table_name='sketches')
    op.drop_table('sketches')
    op.drop_index(op.f('ix_decision_log_id'), table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index(op.f('ix_concept_families_id'), table_name='concept_families')
    op.drop_table('concept_families')
    op.drop_index(op.f('ix_projects_workshop_share_token'), table_name='projects')
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lmkc_entries_id'), table_name='lmkc_entries')
    op.drop_index(op.f('ix_lmkc_entries_doc_id'), table_name='lmkc_entries')
    op.drop_index(op.f('ix_lmkc_entries_category'), table_name='lmkc_entries')
    op.drop_table('lmkc_entries')
    # ### end Alembic commands ###
